Fix `dijit/Calendar` flat theme styles for 1.11+
dojo/dijit-themes pull request #39
Opened 2017-03-16 14:58 UTC by mwistrand

Resolves #38.

Update the theme tester to use Dojo 1.12.1, and update the flat theme styles for `dijit/Calendar` to correctly render the previous/next arrows.

2017-03-18 01:56 UTC, dylans requested changes

2017-03-18 01:56 UTC, dylans commented on flat/dijit/Calendar.css
> +  padding-left: 4px/2;
I assume this is fine, but I wonder why Stylus doesn't do the math as part of the transpilation process.

2017-03-18 01:56 UTC, dylans commented on flat/tests/flat.html
> +<script src="//ajax.googleapis.com/ajax/libs/dojo/1.12.1/dojo/dojo.js"></script>
We're probably better off pointing to //archive.dojotoolkit.org/cdn/1.12.2-cdn/1.12.2/dojo/dojo.js so this can be kept current. That said, we probably need a better way to maintain this version so it doesn't get stale again.

2017-03-19 19:52 UTC, dylans approved these changes

2017-03-19 19:53 UTC, merged

2017-04-07 12:44 UTC, arndbeissner commented
Dylan, FYI: this also resolves https://bugs.dojotoolkit.org/ticket/18931#no1